individual(yes, [doctor, milan, classic, no, no, technologyshare, family]).
individual(yes, [doctor, krakow, gold, car, shortterm, no, no]).
individual(yes, [military, munich, gold, no, no, no, regular]).
individual(yes, [doctor, catanzaro, classic, car, longterm, technologyshare, senior]).
individual(yes, [energy, poznan, gold, apartment, longterm, no, no]).
individual(yes, [doctor, rome, gold, apartment, shortterm, no, regular]).
individual(yes, [finance, bavaria, gold, no, shortterm, globalshare, no]).
individual(yes, [health-care, frankfurt, classic, car, no, globalshare, family]).
individual(yes, [military, warsaw, gold, no, shortterm, no, regular]).
individual(yes, [education, latina, gold, apartment, shortterm, no, family]).
individual(yes, [health-care, karlsruhe, classic, apartment, no, europeshare, no]).
individual(yes, [retail, munich, classic, car, longterm, technologyshare, regular]).
individual(yes, [education, catanzaro, gold, car, no, no, no]).
individual(yes, [doctor, milan, classic, no, no, europeshare, shortterm]).
individual(yes, [police, munich, gold, apartment, no, no, no]).
individual(no, [retail, stuttgart, classic, car, longterm, technologyshare, no]).
individual(no, [finance, brescia, gold, apartment, no, europeshare, regular]).
individual(no, [administration, tarnow, classic, car, no, no, senior]).
individual(no, [materials, freiburg, gold, apartment, shortterm, globalshare, no]).
individual(no, [doctor, poznan, classic, personal, shortterm, europeshare, regular]).
individual(no, [administration, cosenza, classic, car, no, no, no]).
individual(no, [unemployed, munich, classic, car, no, no, no]).
individual(no, [military, kalisz, classic, apartment, shortterm, europeshare, regular]).
individual(no, [manufacturing, cosenza, gold, apartment, longterm, no, no]).
individual(no, [transportation, cosenza, classic, car, shortterm, no, family]).
individual(no, [police, tarnow, gold, apartment, no, no, no]).
individual(no, [nurse, radom, classic, no, no, no, senior]).
individual(no, [education, catanzaro, classic, apartment, no, no, no]).
individual(no, [transportation, warsaw, gold, car, shortterm, technologyshare, regular]).
individual(no, [police, cosenza, classic, car, no, no, no]).
