# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gsegs.ui'
#
# Created: Wed Nov 16 13:27:12 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(492, 594)
        self.okButton = QtGui.QPushButton(Form)
        self.okButton.setGeometry(QtCore.QRect(390, 560, 93, 27))
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 491, 61))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.serviceLineEdit = QtGui.QLineEdit(self.groupBox)
        self.serviceLineEdit.setGeometry(QtCore.QRect(10, 20, 441, 27))
        self.serviceLineEdit.setObjectName(_fromUtf8("serviceLineEdit"))
        self.checkServiceButton = QtGui.QPushButton(self.groupBox)
        self.checkServiceButton.setGeometry(QtCore.QRect(460, 20, 21, 27))
        self.checkServiceButton.setObjectName(_fromUtf8("checkServiceButton"))
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 70, 491, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.classValComboBox = QtGui.QComboBox(self.groupBox_3)
        self.classValComboBox.setGeometry(QtCore.QRect(260, 50, 121, 31))
        self.classValComboBox.setObjectName(_fromUtf8("classValComboBox"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(120, 50, 121, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.rankedRadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.rankedRadioButton.setGeometry(QtCore.QRect(260, 20, 101, 21))
        self.rankedRadioButton.setObjectName(_fromUtf8("rankedRadioButton"))
        self.labelledRadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.labelledRadioButton.setGeometry(QtCore.QRect(120, 20, 101, 21))
        self.labelledRadioButton.setObjectName(_fromUtf8("labelledRadioButton"))
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 170, 251, 171))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 121, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(20, 60, 141, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(20, 90, 171, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.minSizeSGSpinBox = QtGui.QSpinBox(self.groupBox_4)
        self.minSizeSGSpinBox.setGeometry(QtCore.QRect(180, 30, 55, 27))
        self.minSizeSGSpinBox.setMinimum(1)
        self.minSizeSGSpinBox.setObjectName(_fromUtf8("minSizeSGSpinBox"))
        self.maxNumTermsSpinBox = QtGui.QSpinBox(self.groupBox_4)
        self.maxNumTermsSpinBox.setGeometry(QtCore.QRect(180, 60, 55, 27))
        self.maxNumTermsSpinBox.setMinimum(1)
        self.maxNumTermsSpinBox.setObjectName(_fromUtf8("maxNumTermsSpinBox"))
        self.maxNumSGSpinBox = QtGui.QSpinBox(self.groupBox_4)
        self.maxNumSGSpinBox.setGeometry(QtCore.QRect(180, 90, 55, 27))
        self.maxNumSGSpinBox.setMinimum(1)
        self.maxNumSGSpinBox.setMaximum(99)
        self.maxNumSGSpinBox.setObjectName(_fromUtf8("maxNumSGSpinBox"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 48, 14))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cutoffSpinBox = QtGui.QSpinBox(self.groupBox_4)
        self.cutoffSpinBox.setGeometry(QtCore.QRect(180, 120, 55, 27))
        self.cutoffSpinBox.setMinimum(1)
        self.cutoffSpinBox.setMaximum(999)
        self.cutoffSpinBox.setSingleStep(1)
        self.cutoffSpinBox.setProperty(_fromUtf8("value"), 300)
        self.cutoffSpinBox.setObjectName(_fromUtf8("cutoffSpinBox"))
        self.groupBox_5 = QtGui.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(260, 170, 231, 171))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(20, 90, 91, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.randomSeedSpinBox = QtGui.QSpinBox(self.groupBox_5)
        self.randomSeedSpinBox.setGeometry(QtCore.QRect(160, 90, 55, 27))
        self.randomSeedSpinBox.setObjectName(_fromUtf8("randomSeedSpinBox"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(20, 60, 141, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.kSpinBox = QtGui.QSpinBox(self.groupBox_5)
        self.kSpinBox.setGeometry(QtCore.QRect(160, 60, 55, 27))
        self.kSpinBox.setMinimum(1)
        self.kSpinBox.setProperty(_fromUtf8("value"), 5)
        self.kSpinBox.setObjectName(_fromUtf8("kSpinBox"))
        self.summarizeCheckBox = QtGui.QCheckBox(self.groupBox_5)
        self.summarizeCheckBox.setGeometry(QtCore.QRect(20, 30, 141, 21))
        self.summarizeCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.summarizeCheckBox.setObjectName(_fromUtf8("summarizeCheckBox"))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 420, 491, 131))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.legacyCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.legacyCheckBox.setGeometry(QtCore.QRect(10, 20, 161, 21))
        self.legacyCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.legacyCheckBox.setObjectName(_fromUtf8("legacyCheckBox"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 50, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(50, 80, 48, 14))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.fisherSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.fisherSpinBox.setGeometry(QtCore.QRect(90, 70, 62, 31))
        self.fisherSpinBox.setSingleStep(0.01)
        self.fisherSpinBox.setObjectName(_fromUtf8("fisherSpinBox"))
        self.gseaSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.gseaSpinBox.setGeometry(QtCore.QRect(220, 70, 62, 31))
        self.gseaSpinBox.setSingleStep(0.01)
        self.gseaSpinBox.setProperty(_fromUtf8("value"), 1.0)
        self.gseaSpinBox.setObjectName(_fromUtf8("gseaSpinBox"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(180, 80, 48, 14))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pageSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.pageSpinBox.setGeometry(QtCore.QRect(350, 70, 62, 31))
        self.pageSpinBox.setSingleStep(0.01)
        self.pageSpinBox.setProperty(_fromUtf8("value"), 1.0)
        self.pageSpinBox.setObjectName(_fromUtf8("pageSpinBox"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(310, 80, 48, 14))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pValueComboBox = QtGui.QComboBox(self.groupBox_2)
        self.pValueComboBox.setGeometry(QtCore.QRect(140, 110, 78, 23))
        self.pValueComboBox.setObjectName(_fromUtf8("pValueComboBox"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 91, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.groupBox_6 = QtGui.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 340, 491, 80))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 41, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.level_ont1SpinBox = QtGui.QSpinBox(self.groupBox_6)
        self.level_ont1SpinBox.setGeometry(QtCore.QRect(60, 30, 55, 27))
        self.level_ont1SpinBox.setMinimum(1)
        self.level_ont1SpinBox.setObjectName(_fromUtf8("level_ont1SpinBox"))
        self.level_ont2SpinBox = QtGui.QSpinBox(self.groupBox_6)
        self.level_ont2SpinBox.setGeometry(QtCore.QRect(180, 30, 55, 27))
        self.level_ont2SpinBox.setMinimum(1)
        self.level_ont2SpinBox.setObjectName(_fromUtf8("level_ont2SpinBox"))
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(130, 30, 41, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.level_ont3SpinBox = QtGui.QSpinBox(self.groupBox_6)
        self.level_ont3SpinBox.setGeometry(QtCore.QRect(300, 30, 55, 27))
        self.level_ont3SpinBox.setMinimum(1)
        self.level_ont3SpinBox.setObjectName(_fromUtf8("level_ont3SpinBox"))
        self.label_16 = QtGui.QLabel(self.groupBox_6)
        self.label_16.setGeometry(QtCore.QRect(250, 30, 41, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.level_ont4SpinBox = QtGui.QSpinBox(self.groupBox_6)
        self.level_ont4SpinBox.setGeometry(QtCore.QRect(420, 30, 55, 27))
        self.level_ont4SpinBox.setMinimum(1)
        self.level_ont4SpinBox.setObjectName(_fromUtf8("level_ont4SpinBox"))
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(370, 30, 41, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "g-SEGS", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Form", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Service", None, QtGui.QApplication.UnicodeUTF8))
        self.checkServiceButton.setText(QtGui.QApplication.translate("Form", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Target attribute value:", None, QtGui.QApplication.UnicodeUTF8))
        self.rankedRadioButton.setText(QtGui.QApplication.translate("Form", "Ranked data", None, QtGui.QApplication.UnicodeUTF8))
        self.labelledRadioButton.setText(QtGui.QApplication.translate("Form", "Labelled data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Search constraints", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Min subgroup size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Max number of terms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Max number of subgroups", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Random seed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Max times covered (wracc)", None, QtGui.QApplication.UnicodeUTF8))
        self.summarizeCheckBox.setText(QtGui.QApplication.translate("Form", "Summarize descriptions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Legacy settings", None, QtGui.QApplication.UnicodeUTF8))
        self.legacyCheckBox.setText(QtGui.QApplication.translate("Form", "Use legacy SEGS ontology", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Combine p-values:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Fisher", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "GSEA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "PAGE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Maximal p-value", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Form", "General concept levels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Ont 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Ont 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Ont 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Ont 4", None, QtGui.QApplication.UnicodeUTF8))

